version: '3.8'

services:
  hangfire-mysql:
    image: mysql:8.0
    container_name: hangfire-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root # haslo root
      MYSQL_DATABASE: hangfiredb   # dane do logowania
      MYSQL_USER: hangfire
      MYSQL_PASSWORD: Zaq12wsx
    ports:
      - "3308:3306"  # port na kompie 3008
    volumes:
      - hangfire-mysql-data:/var/lib/mysql

volumes:
  hangfire-mysql-data:


# docker-compose up -d (terminal w folderze gdzie jest ten plik)